# Generated by Django 4.0.4 on 2022-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShort', '0002_alter_urltoshort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltoshort',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
